sudo: required
services:
  - docker

before_install:
  - docker build -t mertcancam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mertcancam/react-test npm test -- --coverage

after_success:
  - docker build -t mertcancam/multi-client ./client
  - docker build -t mertcancam/multi-nginx ./nginx
  - docker build -t mertcancam/multi-server ./server
  - docker build -t mertcancam/multi-worker ./worker

# log in to the docker CLI

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take those images and push thm to docker hub

- docker push mertcancam/multi-client
- docker push mertcancam/multi-nginx
- docker push mertcancam/multi-server
- docker push mertcancam/multi-worker